/*
FINITE STATE PATTERN

START,
SUCCESS,
FAILURE
*/

export const FETCH_STRAIN_START = 'FETCH_STRAIN_START';
export const FETCH_STRAIN_SUCCESS = 'FETCH_STRAIN_SUCCESS';
export const FETCH_STRAIN_FAILURE = 'FETCH_STRAIN_FAILURE';
